In [1]:
import numpy as np
import sympy as sp
from kuka_kinematics.geometric_ik import KukaGeometricIK
from manipulator_graph.kinematics_dag import KinematicsDag
from manipulator_graph import URDFParser

parser = URDFParser('./kr210.urdf')
dag = KinematicsDag(parser.joints)
ik = KukaGeometricIK(dag)

In [2]:
graph = dag[0].graph
links = graph.dh_links
joints = [x.joint for x in links]

In [3]:
current_state = {x: 0 for x in joints}

In [10]:
example_state = {x: 0.7 for x in joints}

In [11]:
forward = graph.forward(example_state)
urdf = graph.forward(example_state, return_dh=False)
eef = urdf[-1][1]

In [12]:
ik.infer_joints(current_state, eef)

(0.69999999999999574,)


{'joint_1': 0.70000000000000007,
 'joint_2': 0.69999999999999574,
 'joint_3': 0.70000000000000129,
 'joint_4': 0.69999999999999563,
 'joint_5': 0.70000000000000095,
 'joint_6': 0.70000000000000573}

In [7]:
print eef

[[ 0.90181167 -0.04034915  0.4302414   2.20524832]
 [ 0.14674969  0.96505764 -0.21709051  0.31672617]
 [-0.40644833  0.25891254  0.87622146  1.39818568]
 [ 0.          0.          0.          1.        ]]


In [8]:
def round_print(name, vec):
    ret = np.around(vec, 4)
    print name, ret

In [9]:
round_print('', eef)

 [[ 0.    -0.     1.     1.85 ]
 [-0.     1.     0.     0.   ]
 [-1.    -0.     0.     1.946]
 [ 0.     0.     0.     1.   ]]
