In [1]:
import numpy as np

In [3]:
def cross_skew_matrix(omega):
  x, y, z = omega
  ret = [[0, -z, y], [z, 0, -x], [-y, x, 0]]
  return np.array(ret)

In [4]:
a = np.array([1, 2, 3], dtype=np.float64)
b = np.array([4, 5, 6], dtype=np.float64)
print(np.cross(a, b))

[-3.  6. -3.]


In [5]:
mat = cross_skew_matrix(a)
print np.matmul(mat, b)

[-3.  6. -3.]


In [27]:
def solve_planar_intersection(line1, line2):
  p1, k1 = line1
  p2, k2 = line2
  omega1 = cross_skew_matrix(k1)
  omega2 = cross_skew_matrix(k2)
  w = np.vstack([omega1, omega2])
  b1 = np.cross(k1, p1)
  b2 = np.cross(k2, p2)
  b = np.concatenate((b1, b2), axis=-1)
  ret = np.linalg.lstsq(w, b)[0]
  return ret

In [30]:
p1 = np.array([0., 0., 0.])
p2 = np.array([0., 1., 0.])
k1 = np.array([1.0, 0, 0])
k2 = np.array([-1., -1., 0])
solve_planar_intersection((p1, k1), (p2, k2))

array([-1.,  0.,  0.])