In [1]:
import numpy as np
from manipulator_graph.kinematics_dag import KinematicsDag
from manipulator_graph.kinematics_dag import joint_topology
from manipulator_graph.kinematics_dag import partition_as_serial_dag
from manipulator_graph import URDFParser
from manipulator_graph.kinematics_dag import KinematicsDag
parser = URDFParser('./kr210.urdf')
dag = KinematicsDag(parser.joints)

In [2]:
def round_print(name, vec):
    ret = np.around(vec, 4)
    print name, ret

In [3]:
graph = dag[0].graph
dh_parameter = graph.dh_parameter

In [4]:
dh_parameter

(DHValue(a=0.0, alpha=0, d=0.0, theta=0),
 DHValue(a=0.34999999999999998, alpha=-1.5707963267948966, d=0.0, theta=-1.5707963267948966),
 DHValue(a=1.25, alpha=0, d=0.0, theta=3.141592653589793),
 DHValue(a=0.053999999999999999, alpha=1.5707963267948966, d=1.5, theta=3.141592653589793),
 DHValue(a=0.0, alpha=1.5707963267948966, d=0.0, theta=3.141592653589793),
 DHValue(a=-0.0, alpha=1.5707963267948966, d=0.0, theta=0))

In [5]:
links = graph.dh_links
joints = [x.joint for x in links]
print joints

[u'joint_1', u'joint_2', u'joint_3', u'joint_4', u'joint_5', u'joint_6']


In [6]:
example_state = {x: 0 for x in joints}

In [7]:
forward = graph.forward(example_state)
eef = forward[-1][1]

In [9]:
def extract_position(hm):
    return hm[:3, 3]

In [12]:
def infer_waist_state(wc):
    return np.arctan2(wc[1], wc[0])

In [14]:
import sympy as sp

In [ ]:
shoulder_position = 0
upper_arm_length = 0
lower_arm_length =
def infer_elbow_state()

In [33]:
cos_shoulder = abs_shoulder
abs_shoulder = np.arccos(cos_shoulder)

In [38]:
wc_angle = np.arctan2(wc_trans[0], wc_trans[2])

In [37]:
np.pi / 4

0.7853981633974483

In [39]:
wc_angle

-3.2489804232341653e-15

In [40]:
wc_trans

array([ -3.88578059e-15,  -9.07250796e-25,   1.19600000e+00])

In [48]:
round_print('fw', forward[4][1])

fw [[-0.     0.     1.     1.85 ]
 [ 0.    -1.     0.     0.   ]
 [ 1.     0.     0.     1.946]
 [ 0.     0.     0.     1.   ]]


In [47]:
round_print('wc', wc)

wc [ 0.35  -0.     1.946]


In [29]:
links = graph.dh_links
joints = [x.joint for x in links]
print joints
example_state = {x: 0 for x in joints}
print example_state

[u'joint_1', u'joint_2', u'joint_3', u'joint_4', u'joint_5', u'joint_6']
{u'joint_6': 0, u'joint_4': 0, u'joint_5': 0, u'joint_2': 0, u'joint_3': 0, u'joint_1': 0}


In [30]:
urdf_forward = graph.forward(example_state, return_dh=False)
forward = graph.forward(example_state)
eef = urdf_forward[-1][1]
eef_link = graph.fixed_links[-1]
eef_trans = eef_link.rel

In [34]:
def infer_wrist_center(hm_eff):
    return np.matmul(hm_eff, np.linalg.inv(eef_trans))
round_print('', eef)
round_print('', eef_trans)
wc = infer_wrist_center(eef)
round_print('wc hm', wc)
round_print('wc truth', forward[-1][1])

 [[ 1.    -0.    -0.     2.153]
 [ 0.     1.     0.     0.   ]
 [ 0.    -0.     1.     1.946]
 [ 0.     0.     0.     1.   ]]
 [[ 0.     0.    -1.     0.   ]
 [ 0.     1.     0.     0.   ]
 [ 1.     0.     0.     0.303]
 [ 0.     0.     0.     1.   ]]
wc hm [[ 0.    -0.     1.     1.85 ]
 [-0.     1.     0.     0.   ]
 [-1.    -0.     0.     1.946]
 [ 0.     0.     0.     1.   ]]
wc truth [[ 0.    -0.     1.     1.85 ]
 [-0.     1.     0.     0.   ]
 [-1.    -0.     0.     1.946]
 [ 0.     0.     0.     1.   ]]


In [138]:
wc_pos = extract_position(wc)
def infer_waist_state(pos):
    return np.arctan2(pos[1], pos[0])
waist_state = infer_waist_state(wc_pos)
round_print('waist', waist_state)

waist 0.2


In [139]:
# rotate the whole structure to x-z plane for geometric analysis
rot = sp.rot_axis3(waist_state)
rot = np.array(rot.tolist(), dtype=np.float32)
wc_rot = np.matmul(rot, wc_pos)
shoulder_position = extract_position(graph.dh_frames[2])
wc_trans = wc_rot - shoulder_position
round_print('should_pos', shoulder_position)
round_print('wc_rot', wc_rot)
round_print('wc_trans', wc_trans)

should_pos [ 0.35  0.    0.75]
wc_rot [ 1.9511  0.      1.5213]
wc_trans [ 1.6011  0.      0.7713]


In [140]:
upper_arm_length = np.linalg.norm(extract_position(graph.dh_frames[3]) - extract_position(graph.dh_frames[2]))
lower_arm_length = np.linalg.norm(extract_position(graph.dh_frames[4]) - extract_position(graph.dh_frames[3]))
wc_norm = np.linalg.norm(wc_trans)
abs_shoulder = (wc_norm ** 2 + upper_arm_length ** 2 -  lower_arm_length ** 2) / (2 * wc_norm * upper_arm_length)
abs_shoulder = np.arccos(abs_shoulder)

In [141]:
wc_angle = np.arctan2(wc_trans[2], wc_trans[0])

In [142]:
abs_shoulder

0.98184740938848736

In [143]:
upper_arm_length = np.linalg.norm(extract_position(forward[3][1]) - extract_position(forward[2][1]))
lower_arm_length = np.linalg.norm(extract_position(forward[4][1]) - extract_position(forward[3][1]))

In [144]:
shoulder_solu1 = wc_angle + abs_shoulder
shoulder_solu2 = wc_angle - abs_shoulder

In [145]:
def infer_shoulder_state(solu):
    return np.pi / 2 - solu

In [166]:
shoulder_state = infer_shoulder_state(shoulder_solu1)

In [200]:
def forward_to_elbow(waist_state, shoulder_state):
    base_frame = graph.dh_frames[0]
    waist_hm = np.matmul(base_frame, graph.dh_links[0](waist_state))
    shoulder_hm = np.matmul(waist_hm, graph.dh_links[1](shoulder_state))
    elbow_zero = np.matmul(shoulder_hm, graph.dh_links[2](0))
    elbow_axis = elbow_zero[:3, 2]
    wc_zero = np.matmul(elbow_zero, graph.dh_links[3](0))
    wc_zero = extract_position(wc_zero)
    wc_elbow_zero = wc_zero - elbow_pos
    return extract_position(elbow_zero), elbow_axis, wc_elbow_zero

In [201]:
elbow_pos, elbow_axis, wc_elbow_zero = forward_to_elbow(waist_state, shoulder_state)
round_print('elbow_pos', elbow_pos)
round_print('elbow', extract_position(forward[3][1]))
round_print('wc_pos', wc_pos)
round_print('wc_pos_truth', extract_position(forward[4][1]))
wc_elbow = wc_pos - elbow_pos
round_print('wc_elbow', wc_elbow)

elbow_pos [ 0.514   0.1042  1.9878]
elbow [ 0.514   0.1042  1.9878]
wc_pos [ 1.9122  0.3876  1.5213]
wc_pos_truth [ 1.9122  0.3876  1.5213]
wc_elbow [ 1.3982  0.2834 -0.4664]


In [190]:
def inference_angle(left, right, reference):
    
    cosine = inner_prod(left, right)
    lesser_angle = np.arctan2(
        np.sqrt(1 - cosine * cosine), cosine)
    if np.abs(lesser_angle) < ZERO_TOLERANCE:
        angle = 0
    # atan2 is not continuous around (-1, 0)
    elif np.abs(lesser_angle - np.pi) < ZERO_TOLERANCE:
        angle = np.pi
    else:
        ori = np.cross(left, right)
        sign = np.sign(inner_prod(ori, reference))
        angle = lesser_angle * sign
    return angle

In [202]:
ZERO_TOLERANCE = 1e-6

def normalize(k):
  k = k / np.linalg.norm(k)
  return k

def inner_prod(a, b):
    return (a * b).sum(axis=-1)

angle = inference_angle(normalize(wc_elbow_zero),normalize(wc_elbow), normalize(elbow_axis))

In [203]:
print angle

0.139999975635
