In [1]:
import numpy as np
from manipulator_graph import line_geometry as lg

In [2]:
def create_line(k, p):
    k = k / np.linalg.norm(k)
    return lg.Line(k=np.float64(k), p=np.float64(p))

In [3]:
left = create_line([1, 0, 0], [0, 0, 0])
right = create_line([0, 1, 0], [0, 0, 0])
reference = [0, 0, 1]
print('first test:', lg.angle_distance(left, right, reference))

left = create_line([1, 1, 0], [0, 0, 10])
right = create_line([0, 1, 0], [0, 0, 0])
reference = [0, 0, -1]
lg.angle_distance(left, right, reference)
print('second test', lg.angle_distance(left, right, reference))

left = create_line([1, 1, 0], [0, 0, 10])
right = create_line([1, 1, 0], [0, 0, 0])
reference = [0, 0, 1]
lg.angle_distance(left, right, reference)
print('third test', lg.angle_distance(left, right, reference))

left = create_line([-1, -1, 0], [0, 0, 10])
right = create_line([1, 1, 0], [0, 0, 0])
reference = [0, 0, -1]
lg.angle_distance(left, right, reference)
print('last test', lg.angle_distance(left, right, reference))

('first test:', (1.5707963267948966, 0.0))
('second test', (-0.78539816339744839, 10.0))
('third test', (0, -10.0))
('last test', (3.141592653589793, 10.0))


In [4]:
a = np.random.rand(3)
b = np.random.rand((3))
c = np.cross(a, b)
d = np.matmul(lg.cross_skew_matrix(a), b)
print('difference:', np.linalg.norm(c - d))

('difference:', 0.0)


In [10]:
print('parallel test:', lg.parallel([1, 0, 0], [1.1, 0, 0]))
left = create_line(k=[1, 1, 1], p=[0, 0, 0])
right = create_line(k=[1, 1, 1], p=[-0.5, -0.5, -0.5])
print('same line test', lg.same_line(left, right))
right = create_line(k=[1, 1, 1], p=[-0.5, -0.5, -0.51])
print('same line test', lg.same_line(left, right))

('parallel test:', True)
('same line test', True)
('same line test', False)


In [11]:
left = create_line(k=[1, 1, 1], p=[0, 0, 0])
right = create_line(k=[1, 3, 1], p =[1, 3, 1])
print('intersection test:', lg.planar_intersection(left, right))

('intersection test:', array([ 0.,  0.,  0.]))


In [15]:
left = create_line(k=[1, 1, 0], p=[0, 0, 0])
right = create_line(k=[-1, -1, 0], p=[1, 1, 4])
print(lg.parallel_common_normal(left, right))

[ 0. -0.  1.]


In [18]:
# non parallel common normal
left = create_line(k=[1, 1, 0], p=[0, 0, 0])
right = create_line(k=[1, -1, 0], p=[1, -1, 4])
print(lg.nonparallel_common_normal(left, right))

[-0. -0.  1.]


In [19]:
# common normal intersection
left = create_line(k=[1, 1, 0], p=[0, 0, 0])
right = create_line(k=[1, -1, 0], p=[1, -1, 4])
cn = lg.nonparallel_common_normal(left, right)
print("left to right", lg.common_normal_intersection(left, right, cn)))
print()

[ 0.  0.  0.]


In [20]:
cn

array([-0., -0.,  1.])